# Run this Docker compose file using `docker-compose up -d --build`
# No need specify version 2 or 3 in latest Compose specification
services:
  backend:
    build: backend
    image: e2e-automl-backend:latest     
    ports:
      - "8000:8000"
      - "54321:54321"
    volumes:
      - ./backend:/app/backend
    networks:
      - project_network

  frontend:
    build: frontend
    image: e2e-automl-frontend:latest
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app/frontend
    depends_on: 
    - backend
    networks:
      - project_network

networks:
  project_network: