version: '3.9'

services:
  backend:
    build: backend
    image: e2e-automl-backend:latest
    ports:
      - "8000:8000"
      - "54321:54321"
    volumes:
      - ./backend:/app/backend
    networks:
      - project_network

  frontend:
    build: frontend-react
    image: e2e-automl-frontend:latest
    ports:
      - "80:80"
    volumes:
      - ./frontend-react:/app/frontend
    depends_on:
      - backend
    networks:
      - project_network

networks:
  project_network:
